import Head from 'next/head';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  // Fetch data from an API or database
  const res = await fetch('https://jsonplaceholder.typicode.com/posts');
  const data = await res.json();

  // Pass data as props to the page component and stream any updates
  return {
    props: { data },
    revalidate: 60, // Revalidate every 60 seconds
  };
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>getStaticProps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {data.map((item) => (
            <li key={item.id}>{item.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}
